from thieves import Thief
from characters import Character
kenneth = Character(name="Kenneth", sneaky=True, agile=True)
print(kenneth)
print(kenneth.sneaky)
print(kenneth.agile)
#print(kenneth.hide(8))
#print(kenneth.pickpocket())
print('x')
#print(Thief.pickpocket(kenneth))
x = Thief(name='name')
print (x.pickpocket())
print(x)
print('asd')
#print(kenneth.evade())
#print(kenneth.hide(11))