# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20171116_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='course1',
            new_name='course',
        ),
    ]
